Update konten set Finanzamt="Fin.Amt Celle",                        FinanzamtNr="17/204/00145",  FinanzamtVom="27.01.2025" where KontoNr=231; 
Update konten set Finanzamt="Fin.Amt Celle",                        FinanzamtNr="17/204/00145",  FinanzamtVom="27.01.2025" where KontoNr=241;
Update konten set Finanzamt="Fin.Amt für Körperschaften I, Berlin", FinanzamtNr="27/630/51049",  FinanzamtVom="23.05.2014" where KontoNr=232;
Update konten set Finanzamt="Dortmund-Ost",                         FinanzamtNr="317/5942/0309", FinanzamtVom="26.10.2022" where KontoNr=234; 
Update konten set Finanzamt="Dortmund-Ost",                         FinanzamtNr="317/5942/0309", FinanzamtVom="26.10.2022" where KontoNr=247;
Update konten set Finanzamt="Fin.Amt Rotenburg/W.",                 FinanzamtNr="40/201/05110",  FinanzamtVom="25.02.2022" where KontoNr=248; 
Update konten set Finanzamt="Fin.Amt für Körperschaften I, Berlin", FinanzamtNr="27/027/37515",  FinanzamtVom="13.06.2022" where KontoNr=251; 
Update konten set Finanzamt="Fin.Amt Stuttgart-Körperschaften",     FinanzamtNr="99153/09016",   FinanzamtVom="08.10.2012" where KontoNr=254; 
-- Update konten set Finanzamt="",                                     FinanzamtNr="",              FinanzamtVom=""           where KontoNr=235; -- Lutherische Theologische Hochschule
-- Update konten set Finanzamt="",                                     FinanzamtNr="",              FinanzamtVom=""           where KontoNr=243; -- Lutherische Theologische Hochschule
-- Update konten set Finanzamt="",                                     FinanzamtNr="",              FinanzamtVom=""           where KontoNr=236; -- Hilfsfonds der SELK					
-- Update konten set Finanzamt="",                                     FinanzamtNr="",              FinanzamtVom=""           where KontoNr=237; -- Personalkosten der SELK				
-- Update konten set Finanzamt="",                                     FinanzamtNr="",              FinanzamtVom=""           where KontoNr=242; -- Jugendarbeit								
-- Update konten set Finanzamt="",                                     FinanzamtNr="",              FinanzamtVom=""           where KontoNr=244; -- Kirchenmusik					 
-- Update konten set Finanzamt="",                                     FinanzamtNr="",              FinanzamtVom=""           where KontoNr=245; -- Bausteinsammlung			
-- Update konten set Finanzamt="",                                     FinanzamtNr="",              FinanzamtVom=""           where KontoNr=249; -- Kirche und Judentum			