DROP TABLE IF EXISTS BankenAbschluss;
DROP TABLE IF EXISTS Init;
DROP TABLE IF EXISTS Journal;
DROP TABLE IF EXISTS Personen;
DROP TABLE IF EXISTS Banken;
DROP TABLE IF EXISTS Version;
DROP TABLE IF EXISTS SachKonten;
CREATE TABLE [BankenAbschluss] ([BankNr] INTEGER NULL,[Buchungsjahr] INTEGER NULL,[Anfangssaldo] INTEGER NULL,[Abschlusssaldo] INTEGER NULL);
INSERT INTO "BankenAbschluss" VALUES(1,2014,0,0);
INSERT INTO "BankenAbschluss" VALUES(999,2014,0,0);
CREATE TABLE [Init] ([GemeindeName] VARCHAR(100) NULL,[GemeindeStrasse] VARCHAR(100) NULL,[GemeindePLZ] VARCHAR(5) NULL,[GemeindeOrt] VARCHAR(100) NULL,[GemeindeTel] VARCHAR(30) NULL,[RendantName] VARCHAR(100) NULL,[RendantStrasse] VARCHAR(100) NULL,[RendantPLZ] VARCHAR(5) NULL,[RendantOrt] VARCHAR(100) NULL,[RendantTel] VARCHAR(30) NULL,[RendantEMail] VARCHAR(100) NULL,[Passwort] VARCHAR(100) NULL,[Buchungsjahr] INTEGER NULL, [Finanzamt] VARCHAR(100) NULL, [FinanzamtVom] VARCHAR(100) NULL, [FinanzamtNr] VARCHAR(100) NULL);
INSERT INTO "Init" VALUES('Mustergemeinde','Musterstrasse 66','12345','Musterstadt','01234/789','Max Martin Meier','Hauptstr. 12','65432','Irgendwo','01234/8877','a@b.de','GE_Buch',2015,'','','');
CREATE TABLE [Journal] ([LaufendeNr] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,[Datum] DATE NULL,[SachkontoNr] INTEGER NULL,[BankNr] INTEGER NULL,[PersonenID] INTEGER NULL,[Betrag] INTEGER NULL,[Buchungstext] VARCHAR(200) NULL,[Belegnummer] VARCHAR(100) NULL,[BuchungsJahr] INTEGER NULL, [Bemerkung] VARCHAR(200) NULL, [Faelligkeit] DATE NULL, [ResN1] INTEGER NULL, [ResS1] VARCHAR(200) NULL, [ResD1] DATE NULL);
CREATE TABLE [Personen] ([PersonenID] INTEGER PRIMARY KEY NULL,[BriefAnrede] VARCHAR(20) NULL,[Titel] VARCHAR(20) NULL,[Vorname] VARCHAR(100) NULL,[Vorname2] VARCHAR(100) NULL,[Nachname] VARCHAR(100) NULL,[Strasse] VARCHAR(100) NULL,[Land] VARCHAR(3) NULL,[PLZ] VARCHAR(5) NULL,[Ort] VARCHAR(100) NULL,[Ortsteil] VARCHAR(100) NULL,[TelPrivat] VARCHAR(20) NULL,[TelDienst] VARCHAR(20) NULL,[TelMobil] VARCHAR(20) NULL,[eMail] VARCHAR(100) NULL,[LetzterBetrag] INTEGER NULL, [GE_KartID] INTEGER NULL,[Geburtstag] DATE NULL,[Abgang] BOOLEAN NULL);
CREATE TABLE [Banken] ([BankNr] INTEGER PRIMARY KEY AUTOINCREMENT NULL,[Bank] VARCHAR(100) NULL,[Konto] VARCHAR(100) NULL,[Kontostand] INTEGER NULL,[SortPos] INTEGER NULL,[Statistik] INTEGER NULL);
INSERT INTO "Banken" VALUES(1,'Sammelkonto','Durchgangskonto',0,1,20);
INSERT INTO "Banken" VALUES(999,'Sammelkonto','Ausgleichskonto',0,999,20);
CREATE TABLE [Version] ([Version] VARCHAR(10) NULL);
INSERT INTO "Version" VALUES('1.9');
CREATE TABLE [SachKonten] ([SachkontoNr] INTEGER PRIMARY KEY NULL,[Sachkonto] VARCHAR (100) NULL,[LetzterBetrag] INTEGER NULL,[SortPos] INTEGER NULL,[Kontotype] VARCHAR(2) NULL,[Statistik] INTEGER NULL,[Finanzamt] VARCHAR(100) NULL,[FinanzamtVom] VARCHAR(100) NULL,[FinanzamtNr] VARCHAR(100) NULL);
INSERT INTO "SachKonten" VALUES(1,'Sammelkonto',0,100,'D',1,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(23,'Gesamtkirchliche Kollekten',0,230,'DE',23,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(24,'Kollekten und Spenden für Ämter und Werke der SELK',0,240,'DE',24,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(25,'Kollekten und Spenden für Ämter und Werke außerhalb der SELK',0,250,'DE',25,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(39,'Andere Personalaufwendungen',0,390,'A',3,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(41,'Reise- und Sitzungskosten',0,410,'A',41,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(42,'Kraftfahrzeug-Unterhaltung',0,420,'A',42,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(43,'Postgebühren (Porto, Telefon)',0,430,'A',43,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(44,'allg. Verwaltungskosten',0,440,'A',44,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(45,'Aufwendungen für Grundstücke und Gebäude',0,450,'A',45,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(46,'sonstige Sachaufwendungen',0,460,'A',46,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(47,'Aufwendungen, die auf Erstattung angelegt sind (z.B. Gemeindefahrten, Kalender)',0,470,'A',47,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(51,'Publizistik',0,510,'A',51,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(52,'Gottesdienstbedarf',0,520,'A',52,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(53,'Kinder- und Jugendarbeit',0,530,'A',53,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(54,'Alten- und Krankenbetreuung',0,540,'A',54,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(55,'Chöre',0,550,'A',55,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(56,'Sonstige Gemeindekreise, Veranstaltungen der Gemeinde',0,560,'A',56,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(57,'Druckschriften, Gesangbücher',0,570,'A',57,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(58,'Verborgene Not',0,580,'A',58,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(59,'Außerordentliche Aufwendungen',0,590,'A',59,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(61,'Lutherische Theologische Hochschule',0,610,'A',61,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(62,'Projekthilfe',0,620,'A',62,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(63,'Amt für Gemeindedienst',0,630,'A',63,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(64,'Jugendwerk',0,640,'A',64,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(65,'Amt für Kirchenmusik',0,650,'A',65,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(66,'Sonstige Zuschüsse (aus dem Gemeindeetat)',0,660,'A',66,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(67,'Umlagebeiträge an die Kirchenbezirkskasse / Allgemeine Kirchenkasse (AKK)',0,670,'A',67,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(68,'Sonstige Zahlungen an die Kirchenbezirkskasse, an die Sprengelkasse oder an die AKK',0,680,'A',68,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(81,'Erlöse aus Vermögen (Miete, Pacht, Zinsen, Dividende)',0,810,'E',81,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(82,'Zuschüsse und allgemeine Erstattungen',0,820,'E',82,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(84,'Allgemeine Kirchenbeiträge',0,840,'E',84,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(85,'Spenden für gemeindeeigene Zwecke',0,850,'E',85,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(86,'Kollekten für gemeindeeigene Zwecke',0,860,'E',86,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(87,'Sonstige Einnahmen',0,860,'E',87,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(88,'Einnahmen für gemeindeeigene Zwecke',0,880,'E',88,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(93,'Gesamtkirchliche Kollekten',0,930,'DA',93,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(94,'Kollekten und Spenden für Ämter und Werke der SELK',0,940,'DA',94,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(95,'Kollekten und Spenden für Ämter und Werke außerhalb der SELK',0,950,'DA',95,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(231,'Lutherische Kirchenmission',0,231,'DE',231,'Celle (bis 2014)','31.03.2011','17/204/00145');
INSERT INTO "SachKonten" VALUES(232,'Diakonie',0,232,'DE',232,'Stuttgart-Körperschaften','07.02.2012','99015/03670');
INSERT INTO "SachKonten" VALUES(234,'Diasporawerk',0,234,'DE',234,'Dortmund-Ost','02.07.2012','317/5942/0309');
INSERT INTO "SachKonten" VALUES(235,'Lutherische Theologische Hochschule',0,235,'DE',235,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(236,'Hilfsfonds der SELK',0,236,'DE',236,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(237,'Personalkosten der SELK',0,237,'DE',237,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(241,'Lutherische Kirchenmission',0,241,'DE',241,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(242,'Jugendarbeit',0,242,'DE',242,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(243,'Lutherische Theologische Hochschule',0,243,'DE',243,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(244,'Kirchenmusik',0,244,'DE',244,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(245,'Bausteinsammlung',0,245,'DE',245,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(246,'Sonstige',0,246,'DE',246,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(247,'Diasporawerk',0,247,'DE',247,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(248,'Lutherische Stunde',0,248,'DE',248,'Rotenburg/W. (bis 2013)','17.09.2012','40/201/05110');
INSERT INTO "SachKonten" VALUES(249,'Mission unter Israel',0,249,'DE',249,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(251,'Brot für die Welt',0,251,'DE',251,'Stuttgart-Körperschaften','07.02.2012','99015/03670');
INSERT INTO "SachKonten" VALUES(253,'Sonstige',0,253,'DE',253,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(254,'Weltbibelhilfe',0,254,'DE',254,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(931,'Lutherische Kirchenmission',0,931,'DA',931,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(932,'Diakonie',0,932,'DA',932,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(934,'Diasporawerk',0,934,'DA',934,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(935,'Lutherische Theologische Hochschule',0,935,'DA',935,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(936,'Hilfsfonds der SELK',0,936,'DA',936,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(937,'Personalkosten der SELK',0,937,'DA',937,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(941,'Lutherische Kirchenmission',0,941,'DA',941,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(942,'Jugendarbeit',0,942,'DA',942,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(943,'Lutherische Theologische Hochschule',0,943,'DA',943,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(944,'Kirchenmusik',0,944,'DA',944,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(945,'Bausteinsammlung',0,945,'DA',945,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(946,'Sonstige',0,946,'DA',946,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(947,'Diasporawerk',0,947,'DA',947,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(948,'Lutherische Stunde',0,948,'DA',948,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(949,'Mission unter Israel',0,949,'DA',949,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(951,'Brot für die Welt',0,951,'DA',951,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(953,'Sonstige',0,953,'DA',953,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(954,'Weltbibelhilfe',0,954,'DA',954,NULL,NULL,NULL);
INSERT INTO "SachKonten" VALUES(999,'Sammelkonto / Ausgleichskonto',0,999,'D',1,NULL,NULL,NULL);