BEGIN TRANSACTION;
ALTER TABLE BankenAbschluss RENAME COLUMN BankNr TO KontoNr;
delete from BankenAbschluss where ((KontoNr = 1) or (KontoNr = 999));
CREATE TABLE "Konten" ( "KontoNr" INTEGER NOT NULL, "Sortpos" INTEGER, "Statistik" INTEGER, "Name" VARCHAR(100), "Kontotype" VARCHAR(2), "Kontostand" INTEGER, "Finanzamt" VARCHAR(100), "Finanzamtvom" VARCHAR(100), "Finanzamtnr" VARCHAR(100), PRIMARY KEY("KontoNr"));
delete from Banken where ((BankNr = 1) or (BankNr = 999));
delete from Sachkonten where ((SachKontoNr = 1) or (SachKontoNr = 999) or Kontotype="DA");
UPDATE Sachkonten set Kontotype="D" WHERE (Kontotype="DE");
insert into konten ("kontonr", "sortpos", "statistik", "name", "kontotype") select Banknr, sortpos, statistik, (Bank || " " || Konto) AS Name, 'B' from Banken;
insert into konten ("kontonr", "sortpos", "statistik", "name", "kontotype", "kontostand", "finanzamt", "finanzamtvom", "finanzamtnr") select SachkontoNr, sortpos, statistik, sachkonto, kontotype, 0, finanzamt, finanzamtvom, finanzamtnr from sachkonten;
Update konten set kontostand = (Select Anfangssaldo from Bankenabschluss where Bankenabschluss.KontoNr = konten.KontoNr);
drop table Banken;
drop table sachkonten;
CREATE TABLE "journal_temp" ( "LaufendeNr" INTEGER DEFAULT '''''''''''''''1''''''''''''''', "Belegnummer" VARCHAR(100), "Datum" DATE, "BankNr" INTEGER, "Konto_nach" INTEGER, "PersonenID" INTEGER, "Betrag" INTEGER, "Buchungstext" VARCHAR(200), "Bemerkung" VARCHAR(200), "BuchungsJahr" INTEGER, "Aufwandsspende" VARCHAR(10), PRIMARY KEY("LaufendeNr" AUTOINCREMENT) );
insert into journal_temp select LaufendeNr, Belegnummer, Datum, BankNr, SachkontoNr, PersonenID, Betrag, Buchungstext, Bemerkung, BuchungsJahr, ResS1 from journal;
drop table journal;
ALTER TABLE "journal_temp" RENAME TO "Journal";
update journal set konto_nach = konto_nach-70 where (konto_nach>=90) and (konto_nach <99);
update journal set konto_nach = konto_nach-700 where (konto_nach>=900) and (konto_nach <999);
update journal set konto_nach = konto_nach-7000 where (konto_nach>=9000) and (konto_nach <9999);
ALTER TABLE "Personen" drop COLUMN "LetzterBetrag";
CREATE TABLE IF NOT EXISTS "Init_temp" ( "Passwort" VARCHAR(25), "Buchungsjahr" INTEGER, "Version" VARCHAR(10), "GemeindeName" VARCHAR(100), "GemeindeStrasse" VARCHAR(100), "GemeindePLZ" VARCHAR(5), "GemeindeOrt" VARCHAR(100), "GemeindeTel" VARCHAR(30), "RendantName" VARCHAR(100), "RendantStrasse" VARCHAR(100), "RendantPLZ" VARCHAR(5), "RendantOrt" VARCHAR(100), "RendantTel" VARCHAR(30), "RendantEMail" VARCHAR(100), "Finanzamt" VARCHAR(100), "FinanzamtVom" VARCHAR(100), "FinanzamtNr" VARCHAR(100));
insert into Init_temp select "Passwort", "Buchungsjahr", '3.0', "GemeindeName", "GemeindeStrasse", "GemeindePLZ","GemeindeOrt", "GemeindeTel", "RendantName", "RendantStrasse", "RendantPLZ", "RendantOrt", "RendantTel", "RendantEMail", "Finanzamt", "FinanzamtVom", "FinanzamtNr" from Init;
drop table Init;
ALTER TABLE "Init_temp" RENAME TO "Init";
drop table Version;
COMMIT;
vacuum;
