Update SachKonten set SachkontoNr=248, Sachkonto='Lutherische Stunde', SortPos=248, Statistik=248 where SachkontoNr=233;
Update SachKonten set SachkontoNr=948, Sachkonto='Lutherische Stunde', SortPos=948, Statistik=948 where SachkontoNr=933;
Update SachKonten set SachkontoNr=249, Sachkonto='Mission unter Israel', SortPos=249, Statistik=249 where SachkontoNr=252;
Update SachKonten set SachkontoNr=949, Sachkonto='Mission unter Israel', SortPos=949, Statistik=949 where SachkontoNr=952;
Update Journal set SachkontoNr=248 where SachkontoNr=233;
Update Journal set SachkontoNr=948 where SachkontoNr=933;
Update Journal set SachkontoNr=249 where SachkontoNr=252;
Update Journal set SachkontoNr=949 where SachkontoNr=952;
Update SachKonten set Sachkonto='Lutherische Kirchenmission' where SachkontoNr=231;
Update SachKonten set Sachkonto='Diakonie' where SachkontoNr=232;
Update SachKonten set Sachkonto='Lutherische Theologische Hochschule' where SachkontoNr=235;
Update SachKonten set Sachkonto='Hilfsfonds der SELK' where SachkontoNr=236;
Update SachKonten set Sachkonto='Lutherische Kirchenmission' where SachkontoNr=241;
Update SachKonten set Sachkonto='Lutherische Theologische Hochschule' where SachkontoNr=243;
Update SachKonten set Sachkonto='Bausteinsammlung' where SachkontoNr=245;
Update SachKonten set Sachkonto='Lutherische Kirchenmission' where SachkontoNr=931;
Update SachKonten set Sachkonto='Diakonie' where SachkontoNr=932;
Update SachKonten set Sachkonto='Lutherische Theologische Hochschule' where SachkontoNr=935;
Update SachKonten set Sachkonto='Hilfsfonds der SELK' where SachkontoNr=936;
Update SachKonten set Sachkonto='Lutherische Kirchenmission' where SachkontoNr=941;
Update SachKonten set Sachkonto='Lutherische Theologische Hochschule' where SachkontoNr=943;
Update SachKonten set Sachkonto='Bausteinsammlung' where SachkontoNr=945;
Update SachKonten set Sachkonto='Sonstige Gemeindekreise, Veranstaltungen der Gemeinde' where SachkontoNr=56;
Update SachKonten set Sachkonto='Druckschriften, Gesangbücher' where SachkontoNr=57;
Update SachKonten set Sachkonto='Verborgene Not' where SachkontoNr=58;
Update SachKonten set Sachkonto='Außerordentliche Aufwendungen' where SachkontoNr=59;
Update SachKonten set Sachkonto='Sonstige Zuschüsse (aus dem Gemeindeetat)' where SachkontoNr=66;
Update SachKonten set Sachkonto='Umlagebeiträge an die Kirchenbezirkskasse / Allgemeine Kirchenkasse (AKK)' where SachkontoNr=67;
Update SachKonten set Sachkonto='Sonstige Zahlungen an die Kirchenbezirkskasse, an die Sprengelkasse oder an die AKK' where SachkontoNr=68;
Update SachKonten set Sachkonto='Erlöse aus Vermögen (Miete, Pacht, Zinsen, Dividende)' where SachkontoNr=81;
Update SachKonten set Sachkonto='Allgemeine Kirchenbeiträge' where SachkontoNr=84;
Update SachKonten set LetzterBetrag=0; 
INSERT INTO SachKonten SELECT 47,'Aufwendungen, die auf Erstattung angelegt sind (z.B. Gemeindefahrten, Kalender)',0,470,'A',47,NULL,NULL,NULL WHERE NOT EXISTS(SELECT 1 FROM SachKonten WHERE Sachkontonr = 47);
INSERT INTO SachKonten SELECT 61,'Lutherische Theologische Hochschule',0,610,'A',61,NULL,NULL,NULL WHERE NOT EXISTS(SELECT 1 FROM SachKonten WHERE Sachkontonr = 61);
INSERT INTO SachKonten SELECT 62,'Projekthilfe',0,620,'A',62,NULL,NULL,NULL WHERE NOT EXISTS(SELECT 1 FROM SachKonten WHERE Sachkontonr = 62);
INSERT INTO SachKonten SELECT 63,'Amt für Gemeindedienst',0,630,'A',63,NULL,NULL,NULL WHERE NOT EXISTS(SELECT 1 FROM SachKonten WHERE Sachkontonr = 63);
INSERT INTO SachKonten SELECT 64,'Jugendwerk',0,640,'A',64,NULL,NULL,NULL WHERE NOT EXISTS(SELECT 1 FROM SachKonten WHERE Sachkontonr = 64);
INSERT INTO SachKonten SELECT 65,'Amt für Kirchenmusik',0,650,'A',65,NULL,NULL,NULL WHERE NOT EXISTS(SELECT 1 FROM SachKonten WHERE Sachkontonr = 65);
INSERT INTO SachKonten SELECT 88,'Einnahmen für gemeindeeigene Zwecke',0,880,'E',88,NULL,NULL,NULL WHERE NOT EXISTS(SELECT 1 FROM SachKonten WHERE Sachkontonr = 88);
INSERT INTO SachKonten SELECT 237,'Personalkosten der SELK',0,237,'D',237,NULL,NULL,NULL WHERE NOT EXISTS(SELECT 1 FROM SachKonten WHERE Sachkontonr = 237);
INSERT INTO SachKonten SELECT 247,'Diasporawerk',0,247,'D',247,NULL,NULL,NULL WHERE NOT EXISTS(SELECT 1 FROM SachKonten WHERE Sachkontonr = 247);
INSERT INTO SachKonten SELECT 254,'Weltbibelhilfe',0,254,'D',254,NULL,NULL,NULL WHERE NOT EXISTS(SELECT 1 FROM SachKonten WHERE Sachkontonr = 254);
INSERT INTO SachKonten SELECT 937,'Personalkosten der SELK',0,937,'D',937,NULL,NULL,NULL WHERE NOT EXISTS(SELECT 1 FROM SachKonten WHERE Sachkontonr = 937);
INSERT INTO SachKonten SELECT 947,'Diasporawerk',0,947,'D',947,NULL,NULL,NULL WHERE NOT EXISTS(SELECT 1 FROM SachKonten WHERE Sachkontonr = 947);
INSERT INTO SachKonten SELECT 954,'Weltbibelhilfe',0,954,'D',954,NULL,NULL,NULL WHERE NOT EXISTS(SELECT 1 FROM SachKonten WHERE Sachkontonr = 954);
Update Version set version = '1.7';