Update Sachkonten set Sachkonto="Kirche und Judentum"                                                                          where SachkontoNr=251; 
Update Sachkonten set Finanzamt="Fin.Amt Celle",                        FinanzamtNr="17/204/00145",  FinanzamtVom="22.08.2016" where SachkontoNr=231; 
Update Sachkonten set Finanzamt="Fin.Amt Celle",                        FinanzamtNr="17/204/00145",  FinanzamtVom="22.08.2016" where SachkontoNr=241;
Update Sachkonten set Finanzamt="Fin.Amt für Körperschaften I, Berlin", FinanzamtNr="27/630/51049",  FinanzamtVom="23.05.2014" where SachkontoNr=232;
Update Sachkonten set Finanzamt="Dortmund-Ost",                         FinanzamtNr="317/5942/0309", FinanzamtVom="29.09.2015" where SachkontoNr=234; 
Update Sachkonten set Finanzamt="Dortmund-Ost",                         FinanzamtNr="317/5942/0309", FinanzamtVom="29.09.2015" where SachkontoNr=247;
Update Sachkonten set Finanzamt="Fin.Amt Rotenburg/W.",                 FinanzamtNr="40/201/05110",  FinanzamtVom="15.09.2015" where SachkontoNr=248; 
Update Sachkonten set Finanzamt="Fin.Amt Stuttgart-Körperschaften",     FinanzamtNr="99153/09016",   FinanzamtVom="08.10.2012" where SachkontoNr=254; 
-- Update Sachkonten set Finanzamt="",                                     FinanzamtNr="",              FinanzamtVom=""           where SachkontoNr=235; -- Lutherische Theologische Hochschule
-- Update Sachkonten set Finanzamt="",                                     FinanzamtNr="",              FinanzamtVom=""           where SachkontoNr=243; -- Lutherische Theologische Hochschule
-- Update Sachkonten set Finanzamt="",                                     FinanzamtNr="",              FinanzamtVom=""           where SachkontoNr=236; -- Hilfsfonds der SELK					
-- Update Sachkonten set Finanzamt="",                                     FinanzamtNr="",              FinanzamtVom=""           where SachkontoNr=237; -- Personalkosten der SELK				
-- Update Sachkonten set Finanzamt="",                                     FinanzamtNr="",              FinanzamtVom=""           where SachkontoNr=242; -- Jugendarbeit								
-- Update Sachkonten set Finanzamt="",                                     FinanzamtNr="",              FinanzamtVom=""           where SachkontoNr=244; -- Kirchenmusik					 
-- Update Sachkonten set Finanzamt="",                                     FinanzamtNr="",              FinanzamtVom=""           where SachkontoNr=245; -- Bausteinsammlung			
-- Update Sachkonten set Finanzamt="",                                     FinanzamtNr="",              FinanzamtVom=""           where SachkontoNr=249; -- Kirche und Judentum			